print("'Enter the operation you want to per form' 'addtion = +' 'substraction = -' 'multiplication = *' 'division = /'\n")
input_operation = input(operation)
print("Enter the 1st digit\n")
input_1st = input()
print("Enter the 2nd digit\n")
input_2nd = input()
print("Your Answer is ="(input_1st = input(),input_operation = input(),input_2nd = input))
